name: daily_planner
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0-262.3.beta <4.0.0'

dependencies:
  equatable: ^2.0.5
  firebase_core: ^2.21.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0+1
  flutter_switch: ^0.3.2
  flutter_bloc: ^8.1.3
  google_fonts: ^6.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  im_stepper: ^1.0.1+1
  intl: ^0.18.1
  localstorage: ^4.0.1+4
  numberpicker: ^2.1.2
  syncfusion_flutter_calendar: ^23.1.39
  time_planner: ^0.1.2+1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
